package com.rk.terminal.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * Theme colors aligned with the OmnibotApp design tokens
 * (see ui/lib/theme/omni_theme_palette.dart and ui/lib/theme/app_colors.dart).
 *
 * Light mode: cool blue accent (#2C7FEB) on blue-gray surfaces (#F4F7FB).
 * Dark mode: warm neutral surfaces (#151617) with muted sage accent (#98AD90).
 * Error color is #FF6464 in both modes, matching the main app.
 */

/*
 * Light colors
 */
val md_theme_light_primary = Color(0xFF2C7FEB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E7FD)
val md_theme_light_onPrimaryContainer = Color(0xFF0B356E)
val md_theme_light_secondary = Color(0xFF71809B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8EFF8)
val md_theme_light_onSecondaryContainer = Color(0xFF353E53)
val md_theme_light_tertiary = Color(0xFF00AEFF)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5E0E6)
val md_theme_light_onTertiaryContainer = Color(0xFF0A3440)
val md_theme_light_error = Color(0xFFFF6464)
val md_theme_light_errorContainer = Color(0xFFFFE0E0)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF8C2323)
val md_theme_light_background = Color(0xFFF4F7FB)
val md_theme_light_onBackground = Color(0xFF353E53)
val md_theme_light_surface = Color(0xFFF4F7FB)
val md_theme_light_onSurface = Color(0xFF353E53)
val md_theme_light_surfaceVariant = Color(0xFFF0F5FC)
val md_theme_light_onSurfaceVariant = Color(0xFF71809B)
val md_theme_light_outline = Color(0xFFD3DEEC)
val md_theme_light_inverseOnSurface = Color(0xFFF2EFE8)
val md_theme_light_inverseSurface = Color(0xFF1C1E1F)
val md_theme_light_inversePrimary = Color(0xFF98AD90)
val md_theme_light_surfaceTint = Color(0xFF2C7FEB)
val md_theme_light_outlineVariant = Color(0xFFE2EAF4)
val md_theme_light_scrim = Color(0xFF0B1220)
val md_theme_light_surfaceBright = Color(0xFFFFFFFF)
val md_theme_light_surfaceDim = Color(0xFFD9E2EF)
val md_theme_light_surfaceContainer = Color(0xFFF0F5FC)
val md_theme_light_surfaceContainerHigh = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerHighest = Color(0xFFE9F0F9)
val md_theme_light_surfaceContainerLow = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_primaryFixed = Color(0xFFD8E7FD)
val md_theme_light_onPrimaryFixed = Color(0xFF0B356E)
val md_theme_light_primaryFixedDim = Color(0xFFA9CBF9)
val md_theme_light_onPrimaryFixedVariant = Color(0xFF1F62C4)
val md_theme_light_secondaryFixed = Color(0xFFE8EFF8)
val md_theme_light_onSecondaryFixed = Color(0xFF353E53)
val md_theme_light_secondaryFixedDim = Color(0xFFC4D2E4)
val md_theme_light_onSecondaryFixedVariant = Color(0xFF4A5A75)
val md_theme_light_tertiaryFixed = Color(0xFFC5E0E6)
val md_theme_light_onTertiaryFixed = Color(0xFF0A3440)
val md_theme_light_tertiaryFixedDim = Color(0xFF9CC9D6)
val md_theme_light_onTertiaryFixedVariant = Color(0xFF0F5B73)

/* Dark Colors */
val md_theme_dark_primary = Color(0xFF98AD90)
val md_theme_dark_onPrimary = Color(0xFF151617)
val md_theme_dark_primaryContainer = Color(0xFF3E473C)
val md_theme_dark_onPrimaryContainer = Color(0xFFE3EBDE)
val md_theme_dark_secondary = Color(0xFF9AA396)
val md_theme_dark_onSecondary = Color(0xFF151617)
val md_theme_dark_secondaryContainer = Color(0xFF2D3032)
val md_theme_dark_onSecondaryContainer = Color(0xFFF2EFE8)
val md_theme_dark_tertiary = Color(0xFF6FA3BC)
val md_theme_dark_onTertiary = Color(0xFF0E1B22)
val md_theme_dark_tertiaryContainer = Color(0xFF2A3E47)
val md_theme_dark_onTertiaryContainer = Color(0xFFCDE7F2)
val md_theme_dark_error = Color(0xFFFF6464)
val md_theme_dark_errorContainer = Color(0xFF5C2424)
val md_theme_dark_onError = Color(0xFF3D0A0A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDADA)
val md_theme_dark_background = Color(0xFF151617)
val md_theme_dark_onBackground = Color(0xFFF2EFE8)
val md_theme_dark_surface = Color(0xFF151617)
val md_theme_dark_onSurface = Color(0xFFF2EFE8)
val md_theme_dark_surfaceVariant = Color(0xFF242728)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C3B8)
val md_theme_dark_outline = Color(0xFF484C4F)
val md_theme_dark_inverseOnSurface = Color(0xFF353E53)
val md_theme_dark_inverseSurface = Color(0xFFF2EFE8)
val md_theme_dark_inversePrimary = Color(0xFF2C7FEB)
val md_theme_dark_surfaceTint = Color(0xFF98AD90)
val md_theme_dark_outlineVariant = Color(0xFF373A3C)
val md_theme_dark_scrim = Color(0xFF121314)
val md_theme_dark_surfaceBright = Color(0xFF383B3D)
val md_theme_dark_surfaceDim = Color(0xFF0F1011)
val md_theme_dark_surfaceContainer = Color(0xFF242728)
val md_theme_dark_surfaceContainerHigh = Color(0xFF1C1E1F)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2D3032)
val md_theme_dark_surfaceContainerLow = Color(0xFF1C1E1F)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0E0F10)
val md_theme_dark_primaryFixed = Color(0xFFD8E7FD)
val md_theme_dark_onPrimaryFixed = Color(0xFF0B356E)
val md_theme_dark_primaryFixedDim = Color(0xFFA9CBF9)
val md_theme_dark_onPrimaryFixedVariant = Color(0xFF1F62C4)
val md_theme_dark_secondaryFixed = Color(0xFFE8EFF8)
val md_theme_dark_onSecondaryFixed = Color(0xFF353E53)
val md_theme_dark_secondaryFixedDim = Color(0xFFC4D2E4)
val md_theme_dark_onSecondaryFixedVariant = Color(0xFF4A5A75)
val md_theme_dark_tertiaryFixed = Color(0xFFC5E0E6)
val md_theme_dark_onTertiaryFixed = Color(0xFF0A3440)
val md_theme_dark_tertiaryFixedDim = Color(0xFF9CC9D6)
val md_theme_dark_onTertiaryFixedVariant = Color(0xFF0F5B73)
